author: {'name': 'Reece H. Dunn', 'foaf': '/about#me'}
error_pages: {
  '404': '/error/404.html'}
exclude: ['COPYING.CC_BY_30','Makefile','README.md']
start_year: 2010
language: en
namespaces: {
  dc:   'http://purl.org/dc/elements/1.1/',
  dct:  'http://purl.org/dc/terms/',
  doap: 'http://usefulinc.com/ns/doap#',
  foaf: 'http://xmlns.com/foaf/0.1/',
  rdf:  'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
  s:    'http://schema.org/',
  v:    'http://rdf.data-vocabulary.org/#',
  xsd:  'http://www.w3.org/2001/XMLSchema#' }
permalink: /posts/:year-:month-:day/:title.html
stylesheet: /css/main.css
title: Dive Into Programming
url: http://www.reecedunn.co.uk
